name: Comment on PR yaml
on: 
  workflow_dispatch:
  pull_request:

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps: 
    - name: comment starting point
      uses: hasura/comment-progress@v2.1.0
      with:
        github-token: ${{ secrets.PAT }}
        repository: 'layer5labs/meshery-extensions'
        number: "1174"
        id: extension-test
        message: ':rocket: The Extension Test has started, the progress can be seen [here](https://github.com/layer5labs/meshery-extensions-packages/actions/runs/${{ github.run_id }}). '
        recreate: true
