name: Download Release
on:
  pull_request:
    branches:
      - 'master'

jobs:
  release-manager:
    name: fetch release
    runs-on: ubuntu-latest
    steps:
    - name: Set Release extensions
      run: |
        curl -s https://api.github.com/repos/layer5labs/meshery-extensions-packages/releases >> extension_releases.json
        export TAG=$(jq .[0].tag_name extension_releases.json)
        echo "tag=$TAG" >> $GITHUB_ENV
        echo $TAG
    - name: make directories
      run: |
        echo ${{env.tag}}
        echo ${{env}}
        mkdir -p .meshery/provider/Meshery/${{env.tag}}/provider/navigator
    - name: Download Meshery Exttension Package Version ${{env.tag}}
      run: |
        wget https://github.com/layer5labs/meshery-extensions-packages/releases/download/${{env.tag}}/provider-meshery.tar.gz 
        tar -xzf   provider-meshery.tar.gz -C /home/runner/.meshery/provider/Meshery/${{env.tag}}
    - name: show tree
      run: tree .meshery/
    - name: show runner tree
      run: tree /home/runner/.meshery




  
