name: Download Release
on:
  push:
    branches:
      - 'master'

jobs:
  release-manager:
    name: fetch release
    runs-on: ubuntu-latest
    steps:
    - name: Set Release extensions
      run: |
        curl -s https://api.github.com/repos/layer5labs/meshery-extensions-packages/releases >> extension_releases.json
        export TAG=$(jq .[0].tag_name extension_releases.json)
        echo $TAG
    - name: make directories
      run: mkdir -p .meshery/provider/Meshery/${TAG}/provider/navigator
    - name: tree
      run: apt install tree
    - name: show tree
      run: tree .meshery/


  
