name: Pull Request Commentator
on: 
  repository_dispatch: 
  pull_request:

jobs:
  comment-on-pr:
    if: github.event.action == 'dispatch-pr-comment'
    runs-on: ubuntu-latest
    steps:
      - name: PR comment with reactions
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Commented from the github actions ! :wave:
          reactions: eyes, rocket
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: event type
        run: echo ${{ github.event.event_type }}
