name: Pull Request Commentator
on: 
  repository_dispatch: 
  pull_request:

jobs:
  comment-on-pr:
    # if: github.event.action == 'dispatch-pr-comment'
    runs-on: ubuntu-latest
    steps:
      - name: Set PR number
        run: |
          export pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo "PULL_NO=$pull_number" >> $GITHUB_ENV
      - name: PR comment with reactions
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Action Dispatched Successfully ! :wave:
          reactions: rocket
          pr_number: ${{ env.PULL_NO }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
