name: Pull Request Action Dispatcher
on: [repository_dispatch]

jobs:
  build-ui-and-server:
    if: github.event.action == 'dispatch-pr-test'
    uses: Abhishek-kumar09/test/.github/workflows/re-usable-workflow.yml@master
    secrets: inherit