name: Remote Dispatch Action Initiator
on:
  workflow_dispatch:
  pull_request:

jobs:
  ping-pong:
    runs-on: ubuntu-latest
    steps:
      # - name: PING - Dispatch initiating repository event
      #   run: |
      #     curl -X POST https://api.github.com/repos/Abhishek-kumar09/test/dispatches \
      #     -H 'Accept: application/vnd.github.everest-preview+json' \
      #     -u ${{ secrets.PAT_TOK }} \
      #     --data '{"event_type": "dispatch-pr-test", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
      - name: echo branch name
        if: github.event_name == 'pull_request'
        run: |
          echo "BRANCH_NAME=$GITHUB_HEAD_REF" >> $GITHUB_ENV 
      - name: see branch name
        run: echo ${GITHUB_HEAD_REF}
      - name: see branch name from env
        run: echo ${{env.BRANCH_NAME}}


      # - name: ACK - Acknowledge pong from remote repository
      #   if: github.event.action == 'pong'
      #   run: |
      #     echo "PONG received from '${{ github.event.client_payload.repository }}'" && \
      #     curl -X POST https://api.github.com/repos/Abhishek-kumar09/test/dispatches \
      #     -H 'Accept: application/vnd.github.everest-preview+json' \
      #     -u ${{ secrets.ACCESS_TOKEN }} \
      #     --data '{"event_type": "ack", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
