name: Secrets
on:
  push:
    branches: 
      - 'master'
  

jobs:
  show-secret: 
    name: "Show me the secret"
    runs-on: "ubuntu-latest"
    steps: 
    - name: show secret
      run: echo ${{ secrets.MY_SECRET }}